name: medi_express_patients
description: "Medi Express Patients"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  logging: ^1.2.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  dio: ^5.5.0+1
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^10.0.0
  dotted_border: ^2.1.0
  cached_network_image: ^3.4.0
  path: ^1.8.0
  diacritic: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/pngs/logo_splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/fonts/bepro/
    - assets/config/
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: Bepro
      fonts:
        - asset: assets/fonts/bepro/bepro_thin.ttf
          weight: 100
        - asset: assets/fonts/bepro/bepro_thin_italic.ttf
          style: italic
        - asset: assets/fonts/bepro/bepro_light.ttf
          weight: 200
        - asset: assets/fonts/bepro/bepro_light_italic.ttf
          style: italic
        - asset: assets/fonts/bepro/bepro_extra_light.ttf
          weight: 300
        - asset: assets/fonts/bepro/bepro_extra_light_italic.ttf
          style: italic
        - asset: assets/fonts/bepro/bepro_regular.ttf
          weight: 400
        - asset: assets/fonts/bepro/bepro_italic.ttf
          style: italic
        - asset: assets/fonts/bepro/bepro_medium.ttf
          weight: 500
        - asset: assets/fonts/bepro/bepro_medium_italic.ttf
          style: italic
        - asset: assets/fonts/bepro/bepro_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/bepro/bepro_semi_bold_italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/bepro/bepro_bold.ttf
          weight: 700
        - asset: assets/fonts/bepro/bepro_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/bepro/bepro_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/bepro/bepro_extra_bold_italic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/bepro/bepro_black.ttf
          weight: 900
        - asset: assets/fonts/bepro/bepro_black.ttf
          style: italic
          weight: 900

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  color: "#FFFFFF"
  color_dark: "#ffffff"
  image: assets/pngs/logo_splash.png

  android_12:
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/pngs/logo_splash_android_12.png
    icon_background_color: "#FFFFFF"

  # Positioning the image on different platforms
  android_gravity: center  # Options: bottom, center, center_horizontal, center_vertical, fill, etc.
  ios_content_mode: center  # Options: scaleToFill, scaleAspectFit, scaleAspectFill, center, etc.
  web_image_mode: center  # Options: center, contain, stretch, cover

  # Platform specific images
  image_android: assets/pngs/logo_splash.png
  image_ios: assets/pngs/logo_splash.png
  image_web: assets/pngs/logo_splash.png
